// <auto-generated />
using HauerBet;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HauerBet.Migrations
{
    [DbContext(typeof(HauerBetContext))]
    [Migration("20241116021824_addedWager")]
    partial class addedWager
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("HauerBet.Fixture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("AwayLine")
                        .HasColumnType("REAL");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FixtureID")
                        .HasColumnType("INTEGER");

                    b.Property<float>("HomeLine")
                        .HasColumnType("REAL");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Vig")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Fixtures");
                });

            modelBuilder.Entity("HauerBet.Wager", b =>
                {
                    b.Property<int>("Wager_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FixtureID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Payout")
                        .HasColumnType("REAL");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("WagerAmount")
                        .HasColumnType("REAL");

                    b.HasKey("Wager_Id");

                    b.ToTable("Wagers");
                });
#pragma warning restore 612, 618
        }
    }
}
