// <auto-generated />
using HauerBet;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HauerBet.Migrations
{
    [DbContext(typeof(HauerBetContext))]
    [Migration("20250808004201_addLeage")]
    partial class addLeage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("HauerBet.Fixture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("AwayLine")
                        .HasColumnType("REAL");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AwayVig")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FixtureDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FixtureID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("HomeLine")
                        .HasColumnType("REAL");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HomeVig")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Fixtures");
                });

            modelBuilder.Entity("HauerBet.Wager", b =>
                {
                    b.Property<int>("Wager_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FixtureID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Payout")
                        .HasColumnType("REAL");

                    b.Property<float>("Spread")
                        .HasColumnType("REAL");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Team")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Vig")
                        .HasColumnType("INTEGER");

                    b.Property<float>("WagerAmount")
                        .HasColumnType("REAL");

                    b.Property<string>("WagerDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Wager_Id");

                    b.ToTable("Wagers");
                });
#pragma warning restore 612, 618
        }
    }
}
